{
    'name': "HMS App",
    'summary': """ """,
    'description': """ HMS Project """,
    'author': "Mostafa Hassan",
    'category': 'Productivity',
    'version': '17.0.0.1.0',
    'depends': ['base',
                'crm'],
    'application': True,
    'data': [
        'security/hms_security.xml',
        'security/ir.model.access.csv',
        'views/base_menus.xml',
        'views/patient_view.xml',
        'views/department_view.xml',
        'views/doctor_view.xml',
        'views/crm_inherit.xml',
        'wizard/add_patient_wizard.xml',
        'reports/print_patient_report.xml',
    ],
}
